version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:9.4
    ports:
      - "5432"
    env_file:
      - ./deploy/docker-files/.env.db
  redis:
    image: redis:latest
